### ISSUE TITLE
Twitter Direct: `Uncaught SyntaxError: Identifier 'set' has already been declared` error with Tampermonkey

### ISSUE THREAD

**Issue by darkred** [chocolateboy/userscripts#11]
Greetings

First of all thanks a lot for your work, it's great.

This issue is regarding your 'Twitter Direct' script:
it's working fine with (with Chrome 84/Firefox 79) and Violentmonkey 2.12.7
but unfortunately it does't work with Tampermonkey (TM 4.10/TM beta 4.11.6118).

The Console error with Tampermonkey is: `Uncaught SyntaxError: Identifier 'set' has already been declared`
for [line 19](https://github.com/chocolateboy/userscripts/blob/master/src/twitter-direct.user.js#L19) : `const { set } = module.exports`
(there's no such error with Violentmonkey)

Test URL: https://twitter.com/npmstatus/status/1291290208344760327

Thank you

**Comment by chocolateboy** [comment]
Thanks for the kind words and thanks for letting me know. This should be fixed in Twitter Direct v0.3.1.

I'm surprised that Tampermonkey doesn't nest the script scope inside that of the `@require`s like other engines. I've added a note about this to [UncommonJS](https://github.com/chocolateboy/uncommonjs/#Scope).

**Comment by darkred** [comment]
Thank you for the quick response.
